---
name: Type Check (Mypy)

on:
  push:
    branches:
      - main
      - test
    paths-ignore:
      - "**/README*"

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --no-group test --no-group lint --no-group dev

      - name: Check types with mypy
        run: uv run mypy
